version: "3.3"
services:
  frontend:
    build: ./frontend
    command: "-p 3000"
    ports:
     - "3000:3000"
    networks:
      tier:
        ipv4_address: 169.17.0.2

  fastapi:
    build: ./fastapi
    command: "--port 8800"
    networks:
      tier:
        ipv4_address: 169.17.0.3

networks:
  tier:
    driver: bridge
    ipam:
      config:
        - subnet: "169.17.0.0/16"
